// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1UxCsuPplppZDgAggT-w2OoCGf7ZrRnc',
    appId: '1:872370767003:android:9f5a4e8b4fcde27f49723e',
    messagingSenderId: '872370767003',
    projectId: 'videocall-fa0cb',
    storageBucket: 'videocall-fa0cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCm8PCqe4Z1axyoI3FN8f7_brQ6MXUZjM',
    appId: '1:872370767003:ios:71f5aa8c6349d67049723e',
    messagingSenderId: '872370767003',
    projectId: 'videocall-fa0cb',
    storageBucket: 'videocall-fa0cb.appspot.com',
    androidClientId: '872370767003-kucfn9f9smtmldq90iouh0dilv7766kq.apps.googleusercontent.com',
    iosClientId: '872370767003-vkbm6rjca3bggveicb6odbup354jtvab.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoCall',
  );
}
